### ISSUE TITLE
Windscribe IP, Deluge External IP mismatch

### ISSUE THREAD

**Issue by TheOriginalXman** [Kabe0/deluge-windscribe#13] opened 2021-02-18 08:36 UTC
Hi, still running into this issue. Where windscribe connects and shows the vpn IP but a minute later the status command shows my actual IP. When my actual IP is what is shown in the windscribe status command, deluge still shows the vpn IP as the external address, and does not change to what is being shown as the windscribe status.

Is this a known issue? If so which is the correct external IP?

root@9204ae4a2093:/# windscribe status windscribe -- pid: 18, status: running, uptime: 3m, %cpu: 0.0, %mem: 1.6 IP: 172.241.214.243 CONNECTED -- US-W UDP (443)

root@9204ae4a2093:/# windscribe status windscribe -- pid: 18, status: running, uptime: 4m, %cpu: 0.0, %mem: 1.6 IP: 76.xx.xx.xx CONNECTED -- US-W UDP (443)

**Comment by holl595** [comment] 2021-02-18 14:25
I’ve found the Windscribe status command often returns the real IP address rather than the IP of the vpn connection. 

You can see the IP assigned to the vpn tunnel connection with the command **ifconfig tun0**

**Comment by Kabe0** [comment] 2021-02-19 14:55
So by default, the Deluge torrent client is set to only run on the windscribe VPN network, in addition, the firewall is enabled to ensure no data transfers outside of the VPN network. So there should be little risk of packets accidentally making it's way outside the VPN network.

This is possible a windscribe-cli issue. Running ```ifconfig``` in the container should list all your routes. As long as tun0 is set, you should be good.

**Comment by PrajanChauhan** [comment] 2021-02-21 05:18
Got it thanks. Looks like the issue is intermittent as well. Did a reboot of the machine and works fine now.

**Closed** 2021-03-02 17:22 UTC
